[project]
name = 'stxpredmkt'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.market]
path = 'contracts/market.clar'
clarity_version = 2
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
